#include <stdio.h>

//请根据主程序流程，补全此函数
//冰雹产生并输出函数
//注意：输出每个冰雹数时，请按5位对齐输出
void hailstone(int n) 
{
    printf("Hailstone generated by %d:\n",n);
    /**********  Begin **********/
    int count = 1;
    while((n-1)!=0)
    {
    	if(!(n%2))
    	{
    		n = n/2;
    		printf("%5d",n);
		}
		else
		{
			n = 3*n +1;
			printf("%5d",n);
		}
		if(!((count)%6))
		{
			printf("\n");
		}
		count++;
	}


    /**********  End  **********/
    printf("%5d\n",n);
	printf("Number of hailstone generated:%d",count);
}

int main()
{
	int num;
	scanf("%d",&num);
	hailstone(num);
	return 0;
	
}
